id: I588D72A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:35:42+00:00'
last_modified: '2022-06-07T14:15:25.541800+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27512
  title: མཁས་པར་བྱ་བའི་གནས་དྲུག་བསྟན་པ་ཤེས་བྱ་གསལ་བའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DEEC:
      image_group_id: I4458
      title: ''
      total_pages: 82
      order: 1
      base_file: DEEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
