id: P001740
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:47.793744
source_metadata:
  id: bdr:W27512
  title: མཁས་པར་བྱ་བའི་གནས་དྲུག་བསྟན་པ་ཤེས་བྱ་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    0dce5e0953464bcba7b7fad466c905c5:
      image_group_id: I4458
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
